DROP TABLE GENERATIVEAI.SEVERS;

DROP TABLE GENERATIVEAI.WORK_REQUEST;

DROP TABLE GENERATIVEAI.PROMPTS;

DROP TABLE GENERATIVEAI.EVENTS;

CREATE TABLE GENERATIVEAI.SEVERS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (CACHE 5) PRIMARY KEY,
  doc CLOB CONSTRAINT valid_json_servers CHECK (doc IS JSON)
);

CREATE TABLE GENERATIVEAI.WORK_REQUEST (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (CACHE 5) PRIMARY KEY,
  doc CLOB CONSTRAINT valid_json_wr CHECK (doc IS JSON)
);

CREATE TABLE GENERATIVEAI.PROMPTS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (CACHE 5) PRIMARY KEY,
  doc CLOB CONSTRAINT valid_json_prompts CHECK (doc IS JSON)
);

CREATE TABLE GENERATIVEAI.EVENTS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (CACHE 5) PRIMARY KEY,
  doc CLOB CONSTRAINT valid_json_events CHECK (doc IS JSON)
);

INSERT INTO
  GENERATIVEAI.PROMPTS (doc)
VALUES
  (
    '
    {
      "id": "male-general",
      "tag": "male-general",
      "file_path": "prompts/male-general.json",
    }');
INSERT INTO
  GENERATIVEAI.PROMPTS (doc)
VALUES
  (
    '
    {
      "id": "female-general",
      "tag": "female-general",
      "file_path": "prompts/female-general.json",
    }'
  );

INSERT INTO
  GENERATIVEAI.EVENTS (doc)
VALUES
  ('
    {
      "id": "LEAP 2023",
      "event": "LEAP 2023",
      "image_path": "/home/ubuntu/oci-sd-manager/data/ORACLELEAP2023.png",
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '{
        "id": "draspayano@gmail.com",
        "mail": "draspayano@gmail.com",
        "server": "10.0.0.71",
        "tag": "female-general",
        "session": "sohnjjkavs",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
}'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "badr.tharwat@oracle.com",
        "mail": "badr.tharwat@oracle.com",
        "server": "10.0.0.163",
        "tag": "male-general",
        "session": "wjtimmhhec",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "joy.john@oracle.com",
        "mail": "joy.john@oracle.com",
        "server": "10.0.0.71",
        "tag": "male-general",
        "session": "vjdjgspkkq",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "carlos.j.olivares@oracle.com",
        "mail": "carlos.j.olivares@oracle.com",
        "server": "10.0.0.163",
        "tag": "male-general",
        "session": "agpmrabflj",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "blisterdeveloper@gmail.com",
        "mail": "blisterdeveloper@gmail.com",
        "server": "10.0.0.163",
        "tag": "female-general",
        "session": "wnoqhtalhr",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "borja.gomez@oracle.com",
        "mail": "borja.gomez@oracle.com",
        "server": "10.0.0.77",
        "tag": "male-general",
        "session": "twdqwofnva",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "carlgira@gmail.com",
        "mail": "carlgira@gmail.com",
        "server": "10.0.0.232",
        "tag": "male-general",
        "session": "yqpkwrdbwe",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "akram.alnabulsi@gmail.com",
        "mail": "akram.alnabulsi@gmail.com",
        "server": "10.0.0.200",
        "tag": "male-general",
        "session": "bedjolgcyk",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "najla.alkebsi@oracle.com",
        "mail": "najla.alkebsi@oracle.com",
        "server": "10.0.0.38",
        "tag": "female-general",
        "session": "ikgehjdmvb",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "wael.ezzat@gmail.com",
        "mail": "wael.ezzat@gmail.com",
        "server": "10.0.0.32",
        "tag": "male-general",
        "session": "bqvvrfwrak",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "leopoldo.boado@oracle.com",
        "mail": "leopoldo.boado@oracle.com",
        "server": "10.0.0.229",
        "tag": "male-general",
        "session": "jblvkctlmt",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "bo.english@oracle.com",
        "mail": "bo.english@oracle.com",
        "server": "10.0.0.229",
        "tag": "female-general",
        "session": "dkeoakhwtl",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "alexnozu@hotmail.com",
        "mail": "alexnozu@hotmail.com",
        "server": "10.0.0.187",
        "tag": "male-general",
        "session": "edsgohdlso",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "susana.rodriguez.puerta@oracle.com",
        "mail": "susana.rodriguez.puerta@oracle.com",
        "server": "10.0.0.229",
        "tag": "female-general",
        "session": "ccndwnokgd",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "renad.almalki@oracle.com",
        "mail": "renad.almalki@oracle.com",
        "server": "10.0.0.229",
        "tag": "female-general",
        "session": "awrsmdlrtb",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "ricardo.anda@oracle.com",
        "mail": "ricardo.anda@oracle.com",
        "server": "10.0.0.187",
        "tag": "male-general",
        "session": "sjqpifmbfs",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "mohamed.shaaban1@gmail.com",
        "mail": "mohamed.shaaban1@gmail.com",
        "server": "10.0.0.16",
        "tag": "female-general",
        "session": "cqbgvghtoz",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "angel.mogollongonzalez@cgi.com",
        "mail": "angel.mogollongonzalez@cgi.com",
        "server": "10.0.0.250",
        "tag": "male-general",
        "session": "erfofmqdyf",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "jaime.vacascaston@cgi.com",
        "mail": "jaime.vacascaston@cgi.com",
        "server": "10.0.0.16",
        "tag": "male-general",
        "session": "zhknpnssrq",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "mohamed.shaaban1@icloud.com",
        "mail": "mohamed.shaaban1@icloud.com",
        "server": "10.0.0.250",
        "tag": "male-general",
        "session": "haddqmkejv",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "m.diab@kindiplus.com",
        "mail": "m.diab@kindiplus.com",
        "server": "10.0.0.16",
        "tag": "male-general",
        "session": "qwedrcsksk",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "shahad.alasmari@oracle.com",
        "mail": "shahad.alasmari@oracle.com",
        "server": "10.0.0.250",
        "tag": "female-general",
        "session": "vtzzbtedww",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "carlos.delgadocastano@cgi.com",
        "mail": "carlos.delgadocastano@cgi.com",
        "server": "10.0.0.16",
        "tag": "male-general",
        "session": "bllbwkyzoj",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "fatimah.al-matar@oracle.com",
        "mail": "fatimah.al-matar@oracle.com",
        "server": "10.0.0.166",
        "tag": "female-general",
        "session": "eovzdssogq",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "mhamdan71@hotmail.com",
        "mail": "mhamdan71@hotmail.com",
        "server": "10.0.0.166",
        "tag": "male-general",
        "session": "fpjaqwdshv",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );

INSERT INTO
  GENERATIVEAI.WORK_REQUEST (doc)
VALUES
  (
    '
    {
        "id": "wed.alrifai@gmail.com",
        "mail": "wed.alrifai@gmail.com",
        "server": "10.0.0.166",
        "tag": "female-general",
        "session": "dqrapgfibq",
        "status": "image_generation_completed",
        "event": "LEAP 2023"
    }'
  );